---
include:
  - template: Terraform/Base.latest.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.latest.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
variables:
  TF_STATE_NAME: default
  TF_CACHE_KEY: default
stages:
  - validate
  - test
  - build
  - deploy
  - cleanup
fmt:
  extends: ".terraform:fmt"
  needs: []
validate:
  extends: ".terraform:validate"
  needs: []
build:
  extends: ".terraform:build"
  environment:
    name: "$TF_STATE_NAME"
    action: prepare
deploy:
  extends: ".terraform:deploy"
  dependencies:
    - build
  environment:
    name: "$TF_STATE_NAME"
    action: start
